# Generated by Django 5.0.7 on 2024-08-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
